name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run basic check
        run: echo "✅ Auto Locator Pro workflow ran successfully!"
"scripts": {
  "start": "react-scripts start",
  "build": "react-scripts build"
